---

- hosts: all
  remote_user: root
  tasks: 

    - name: Disable dpkg fsync
      raw: test -e /etc/dpkg/dpkg.cfg.d/unsafe-io || echo force-unsafe-io > /etc/dpkg/dpkg.cfg.d/unsafe-io

    - name: Upgrade debian
      apt:
        update_cache: true
        upgrade: true

    - name: Install required debs
      apt:
        name: 
          - dirmngr
          - apt-transport-https
          - aptitude
        state: latest 
        
    - name: Add x2go user
      user:
        name: x2go
        comment: X2Go User
        group: users
        groups: sudo
        generate_ssh_key: yes
        shell: /bin/bash

    - name: Add apt keys
      apt_key:
        keyserver: keys.gnupg.net
        id: "{{ item }}" 
      with_items:
        - E1F958385BFE2B6E
        - 1655A0AB68576280
        - 1C52189C923F6CA9
        - EB3E94ADBE1229CF

    - name: Add repos
      apt_repository: 
        repo: "{{item}}"
        state: present
      with_items:
        - deb http://packages.x2go.org/debian stretch extras main
        - deb https://deb.nodesource.com/node_12.x stretch main
        - deb http://ppa.launchpad.net/ethereum/ethereum/ubuntu xenial main
        - deb https://packages.microsoft.com/repos/vscode stable main

    - name: Install required debs
      apt:
        name: 
          - mate-desktop
          - x2goserver
          - mate-session-manager
          - mate-applets
          - mate-backgrounds
          - mate-control-center
          - mate-desktop-environment
          - dconf-cli
          - ethereum
          - nodejs
          - code
          - git
          - firefox-esr
          - openjdk-11-jdk
          - openssl
          - rhash
          - libdigest-sha3-perl
        state: latest

    - name: remove visual studio repo
      apt_repository: 
        repo: deb https://packages.microsoft.com/repos/vscode stable main
        state: absent
        update_cache: yes

    - name: install libkeccak.so
      copy: 
        src: ./files/libkeccak.so.1.2
        dest: /usr/local/lib
        mode: "0644"

    - name: install keccac-256sum
      copy: 
        src: ./files/keccak-256sum
        dest: /usr/local/bin
        mode: "0755"

    - name: run ldconfig
      command: ldconfig

    - name: download besu binary
      get_url: 
        url: https://bintray.com/api/ui/download/hyperledger-org/besu-repo/besu-1.3.5.tar.gz
        dest: /var/tmp/besu-1.3.5.tar.gz

    - name: install besu binary
      unarchive:
        src: /var/tmp/besu-1.3.5.tar.gz
        dest: /usr/local
        owner: root
        remote_src: yes

    - name: link besu
      file:
        src: /usr/local/besu-1.3.5/bin/besu
        dest: /usr/local/bin/besu
        owner: root
        state: link

    - name: generate a private and public key
      shell: openssl ecparam -name secp256k1 -genkey -noout | openssl ec -text -noout > /home/x2go/key
      args:
        creates: /home/x2go/key
      become: yes
      become_user: x2go

    - name: extract public key
      shell: cat /home/x2go/key | grep pub -A 5 | tail -n +2 | tr -d '\n[:space:]:' | sed 's/^04//' > /home/x2go/pub
      args:
        creates: /home/x2go/pub
      become: yes
      become_user: x2go

    - name: extract private key
      shell: cat /home/x2go/key | grep priv -A 3 | tail -n +2 | tr -d '\n[:space:]:' | sed 's/^00//' > /home/x2go/priv
      args: 
        creates: /home/x2go/priv
      become: yes
      become_user: x2go

    - name: generate address
      shell: cat /home/x2go/pub | keccak-256sum -x -l | tr -d ' -' | tail -c 41 > /home/x2go/address
      args:
        creates: /home/x2go/address
      become: yes
      become_user: x2go

    - name: get address
      shell: cat /home/x2go/address
      register: ethereum_address

    - name: get private key
      shell: cat /home/x2go/priv
      register: ethereum_private_key

    - name: show address
      debug:
        msg: "0x{{ethereum_address.stdout}}" 

    - name: create local directories
      file:
        path: "{{ item }}" 
        recurse: yes
        state: directory
        owner: x2go
      with_items: 
        - /home/x2go/.config/autostart
        - /home/x2go/Desktop
        - /home/x2go/docs
        - /home/x2go/.besu
        - /home/x2go/.besu/{{ ethereum_network_id }}

    - name: get besu key
      shell: besu --data-path=/home/x2go/.besu/{{ ethereum_network_id}} public-key export-address
      become: yes
      become_user: x2go
      register: besu_public_key_address

    - name: show besu public key
      debug: 
        msg: "{{ besu_public_key_address.stdout_lines[1] }}"

    - name: install genesis.json
      template:
        src: files/genesis.json
        dest: /home/x2go/.besu/genesis.json
        owner: x2go

    - name: copy check_wallpaper.sh
      copy:
        src: ./files/check_wallpaper.sh
        dest: /usr/local/bin
        mode: "0755"

    - name: copy check_wallpaper.desktop
      copy: 
        src: ./files/check_wallpaper.desktop
        dest: /home/x2go/.config/autostart
        owner: x2go
        group: users

    - name: copy wallpaper.jpg
      copy: 
        src: ./files/wallpaper.jpg
        dest: /home/x2go
        owner: x2go
        group: users

    - name: copy show_docs.sh
      copy:
        src: ./files/show_docs.sh
        dest: /usr/local/bin
        mode: "0755"

    - name: copy show_docs.desktop
      copy:
        src: ./files/show_docs.desktop
        dest: /home/x2go/.config/autostart
        owner: x2go
        group: users

    - name: copy docs
      template:
        src: ./files/docs/index.html
        dest: /home/x2go/docs
        owner: x2go
        group: users

    - name: copy Mist.desktop
      copy: 
        src: ./files/Mist.desktop
        dest: /home/x2go/Desktop
        owner: x2go
        group: users

    - name: fix sudoers
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: "^%sudo"
        line: "%sudo ALL=NOPASSWD: ALL"

    - name: copy besu.service
      template: 
        src: ./files/besu.service
        dest: /lib/systemd/system
      
    - name: copy run_mist
      copy:
        src: ./files/run_mist
        dest: /usr/local/bin/run_mist
        mode: "0755"

    - name: install truffle
      npm:
        name: truffle@latest
        global: yes

    - name: fugly visual studio fix - grrrr
      command: "sed -i 's/BIG-REQUESTS/_IG-REQUESTS/' /usr/lib/x86_64-linux-gnu/libxcb.so.1"
      args:
        warn: false
        
    - name: fire up besu
      systemd:
        name: besu
        masked: no
        enabled: yes
        state: started
        daemon_reload: yes
