#!/bin/sh

. /etc/default/besu

if [ "$NETWORK" = "DEV" ]; then

    echo "Running Private Development Network"

    if [ -n "$NETWORK_ID" ]; then

        # Check if .ethereum exists
        [ -d ~/.besu ] || mkdir ~/.besu

        # Check if generis file has been generated
        if [ ! -f ~/.besu/genesis.json ]; then

cat <<-EOF  >~/.besu/genesis.json 
    {
        "config": {
            "chainId": $NETWORK_ID,
            "homesteadBlock": 0,
            "eip155Block": 0,
            "eip158Block": 0
        },
        "difficulty": "0x400",
        "gasLimit": "0x8000000",
        "alloc": {}
    }
EOF
        fi

        # Check if .besu/dev exists
        [ -d ~/.besu/DEV ] || mkdir ~/.besu/DEV

        # Check if chain has been created
        if [ ! -d ~/.ethereum/private/geth ]; then
            echo "Create private blockchain"
            geth --identity "$NETWORK" --datadir ~/.ethereum/$NETWORK init ~/.ethereum/genesis.json
        fi

        # Check if account exists
        ACCOUNT_0=`geth --networkid $NETWORK_ID --datadir ~/.ethereum/$NETWORK account list 2>/dev/null`
        if [ -z "$ACCOUNT_0" ]; then
            echo "Creating new account"
            geth --networkid $NETWORK_ID --datadir ~/.ethereum/$NETWORK account new --password ~/.ethereumpwd 2>/dev/null
        fi

        # Finally run geth with miner
        echo "Firing up geth in private mode"
        nice -n 10 geth --networkid $NETWORK_ID --datadir ~/.ethereum/$NETWORK --rpc --rpcport 8545 --rpcapi db,eth,net,web3,personal --verbosity 3 --mine --minerthreads 1

    else 
        echo "Private network with no ID?"
        exit 100
    fi

else

    echo "Firing up geth in testnet mode"
    /usr/bin/geth -${NETWORK} --syncmode fast --rpc --rpcport 8545 --rpcapi db,eth,net,web3,personal 

fi
# vim: ts=4 et nowrap autoindent
